#include "MPort_Interface.h"
#include "MPort_config.h"


 MPORT_ENU_PIN_CONFIGRATIONS_t MPORT_PINCFG[NUMBER_OF_USED_PINS] =
 {
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,

    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW,
    MPORT_enu_OUTPUT_LOW,MPORT_enu_OUTPUT_LOW

 };

